=== IONOS-WordPress/cm4all-wp-impex/jsonschema/slice-content.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Impex Content Slice",
  "description": "a Impex slice containing content",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The JSON schema for this slice"
    },
    "version": {
      "title": "Impex Provider content version",
      "description": "Version will be used by Impex to know what data format to expect",
      "const": "1.0.0"
    },
    "type": {
      "title": "Impex slice type",
      "description": "Value will be used by Impex to know the content type of the slice",
      "const": "php"
    },
    "tag": {
      "title": "Impex slice tag",
      "description": "The Impex slice tag contains information about the responsible Impex provider for this slice",
      "const": "content-exporter"
    },
    "meta": {
      "title": "Metadata for the slice",
      "description": "Metadata is a JSON object used to store additional information about the slice",
      "const": {
        "entity": "content-exporter"
      }
    },
    "data": {
      "type": "object",
      "properties": {
        "posts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/posts-item"
          },
          "minItems": 1,
          "$comment": "@TODO: unique ids are not yet supported by jsonschema",
          "uniqueItems": true
        }
      },
      "title": "Data portion of this Impex slice",
      "description": "data contains the real Impex data.",
      "required": ["posts"]
    }
  },
  "additionalProperties": false,
  "required": ["version", "type", "tag", "meta", "data"],
  "definitions": {
    "posts-item": {
      "title": "WordPress posts stored in this this Impex slice",
      "type": "object",
      "properties": {
        "wp:post_id": {
          "type": "integer",
          "minimum": 1,
          "title": "WordPress post_id",
          "description": "The unique WordPress post id of the post"
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "title": "WordPress post title",
          "description": "The title of the WordPress post as it is stored in the database"
        },
        "wp:post_content": {
          "type": "string",
          "minLength": 1,
          "title": "WordPress post content",
          "description": "The content of the WordPress post",
          "examples": [
            "<!-- wp:paragraph -->\n<p>Hello from first imported post !</p>\n<!-- /wp:paragraph -->",
            "<!-- wp:paragraph -->\n<p>Hello world</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:html -->\n<p>A bit of custom html utilizing the Gutenberg html block</p>\n<ul>\n  <li>hi</li>\n  <li>ho</li>\n  <li>howdy</li>\n</ul><!-- /wp:html -->"
          ]
        },
        "wp:post_type": {
          "title": "WordPress post type",
          "description": "The type of the WordPress post.\nCcontent related post types are 'post' and 'page'.\nIf not declared, type 'post' will be assumed.",
          "type": "string",
          "enum": [
            "post",
            "page",
            "nav_menu_item",
            "wp_template",
            "wp_template_part",
            "wp_block",
            "wp_global_styles"
          ],
          "default": "page"
        },
        "wp:status": {
          "type": "string",
          "title": "WordPress post status",
          "description": "The WordPress post status (https://wordpress.org/support/article/post-status/)",
          "enum": ["publish", "future", "draft", "pending", "private"],
          "default": "draft"
        },
        "wp:post_name": {
          "type": "string",
          "title": "WordPress post slug",
          "description": "Used to generate the permalink. If not given, the sanitized post title will be used instead.",
          "minLength": 1
        },
        "wp:post_parent": {
          "type": "integer",
          "minimum": 1,
          "title": "WordPress post parent id",
          "description": "The WordPress post id of the parent post.\n If not given, the post will be created as a top level post."
        }
      },
      "required": ["wp:post_id", "title", "wp:post_content"],
      "additionalProperties": false
    }
  }
}

=== IONOS-WordPress/cm4all-wp-impex/docs/jsonschema/slice-0001.json
{
  "$schema": "slice-content.json",
  "type": "php",
  "version": "1.0.0",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:post_id": 1,
        "title": "Hello world!",
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello from first imported post !</p>\n<!-- /wp:paragraph -->"
      },
      {
        "wp:post_id": 1,
        "wp:post_type": "post",
        "wp:status": "publish",
        "wp:post_name": "home",
        "wp:post_parent": 1,
        "title": "Home",
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello world</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:html -->\n<p>A bit of custom html utilizing the Gutenberg html block</p>\n<ul>\n  <li>hi</li>\n  <li>ho</li>\n  <li>howdy</li>\n</ul><!-- /wp:html -->"
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/impex-cli/tests/fixtures/simple-import/chunk-0001/slice-0004.json
{
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:status": "publish",
        "wp:post_type": "page",
        "wp:post_name": "page-with-gallery-multiple-images",
        "wp:post_id": 4,
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello world</p>\n<!-- /wp:paragraph -->\n<!-- wp:gallery -->\n<figure class=\"wp-block-gallery has-nested-images columns-default is-cropped\">\n  <!-- wp:image -->\n  <figure class=\"wp-block-image\"><img src=\"./james-wheeler-unsplash.jpg\"/></figure>\n  <!-- /wp:image -->\n\n  <!-- wp:image -->\n  <figure class=\"wp-block-image\"><img src=\"./greysen-johnson-unsplash.jpg\"/></figure>\n  <!-- /wp:image -->\n\n  <!-- wp:image -->\n  <figure class=\"wp-block-image\"><img src=\"./wes-walker-unsplash.jpg\"/></figure>\n  <!-- /wp:image -->\n</figure>\n<!-- /wp:gallery -->",
        "title": "A page with gallery block."
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/impex-cli/tests/fixtures/simple-import/chunk-0001/slice-0003.json
{
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:status": "publish",
        "wp:post_type": "page",
        "wp:post_name": "page-with-image",
        "wp:post_id": 3,
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello world</p>\n<!-- /wp:paragraph -->\n<!-- wp:image --><figure class=\"wp-block-image\"><img src=\"./wes-walker-unsplash.jpg\"/></figure><!-- /wp:image -->",
        "title": "A page with an image block"
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/impex-cli/tests/fixtures/simple-import/chunk-0001/slice-0002.json
{
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:status": "publish",
        "wp:post_type": "page",
        "wp:post_name": "hello-world",
        "wp:post_id": 2,
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello from import !</p>\n<!-- /wp:paragraph -->",
        "title": "Hello world!"
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/impex-cli/tests/fixtures/simple-import/chunk-0001/slice-0005.json
{
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:status": "publish",
        "wp:post_type": "page",
        "wp:post_name": "page-with-custom-html-including-media",
        "wp:post_id": 5,
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello world</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:html -->\n<p>A bit of custom html utilizing the Gutenberg html block</p>\n<ul>\n  <li>hi</li>\n  <li>ho</li>\n  <li>howdy</li>\n</ul>\n<figure class=\"wp-block-image\">\n<img src=\"http://localhost:8889/wp-content/uploads/2022/03/greysen-johnson-unsplash.jpg\" alt=\"\">     <figcaption>Fly fishing</figcaption>\n</figure>\n<!-- /wp:html -->",
        "title": "A page using Gutenberg HTML block."
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/jsonschema/slice-content-example.json
{
  "$schema": "slice-content.json",
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:post_id": 1,
        "title": "Home",
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello from first imported post !</p>\n<!-- /wp:paragraph -->"
      },
      {
        "wp:post_id": 2,
        "title": "About",
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello from \"second imported post\" !</p>\n<!-- /wp:paragraph -->"
      }
    ]
  }
}

=== IONOS-WordPress/cm4all-wp-impex/impex-cli/tests/fixtures/simple-import/chunk-0001/slice-0001.json
{
  "version": "1.0.0",
  "type": "php",
  "tag": "content-exporter",
  "meta": {
    "entity": "content-exporter"
  },
  "data": {
    "posts": [
      {
        "wp:status": "publish",
        "wp:post_type": "post",
        "wp:post_name": "hello-world-first-post",
        "wp:post_id": 1,
        "wp:post_content": "<!-- wp:paragraph -->\n<p>Hello from first imported post !</p>\n<!-- /wp:paragraph -->",
        "title": "Hello first post!"
      }
    ]
  }
}
